SELECT B.TITLE AS 게시글_제목, B.BOARD_ID AS 게시글_ID, R.REPLY_ID AS 댓글_ID, R.WRITER_ID AS 댓글_작성자_ID, R.CONTENTS AS 댓글_내용, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS 댓글_작성일
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') ASC, B.TITLE ASC;